image: Ubuntu1604

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq --no-install-recommends binutils-dev libopenblas-dev liblapack-dev build-essential libboost-all-dev libarmadillo-dev libmlpack-dev 
  - cd $APPVEYOR_BUILD_FOLDER && mkdir build && cd build && cmake -DUSE_OPENMP=OFF ..
  - make -j2
test_script:
  - exit 0

build: off
